# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Kontrol, eylemin ne zaman çalışacağını belirler. Bu eylem her 6 saatte bir çalışır.
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# İş akışındaki çalışma sırası:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate the Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: erenn560
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show the build status
        run: git status

      - name: Set Environment Variables
        run: |
          echo "SNAKE_GIF_PATH=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
          echo "SNAKE_SVG_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

